name: Build static wget for Windows x64

on:

  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:


    - name: Download wget release tarball
      run: curl -LO https://ftp.gnu.org/gnu/wget/wget-latest.tar.gz

    - name: Extract source
      run: tar xf wget-latest.tar.gz

    - name: Install MSYS2
      uses: msys2/setup-msys2@v2
      with:
        update: true
        install: >-
          base-devel
          git
          mingw-w64-x86_64-gcc
          mingw-w64-x86_64-make
          mingw-w64-x86_64-pkg-config
          mingw-w64-x86_64-gnutls
          mingw-w64-x86_64-libidn2
          mingw-w64-x86_64-libiconv
          mingw-w64-x86_64-zlib

    - name: Build static wget
      shell: msys2 {0}
      run: |
        cd wget-1.25.0
        export gl_cv_func_gettimeofday_clobber=no
        export ac_cv_func_daylight=no
        ./configure \
          --host=x86_64-w64-mingw32 \
          --with-ssl=gnutls \
          --disable-nls \
          --enable-ipv6 \
          CFLAGS="-O2 -static" \
          LDFLAGS="-static"
        make -j$(nproc)
        strip src/wget.exe


    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: wget-windows-x64-static
        path: wget-1.25.0/src/wget.exe
