name: Build wget for Windows x64

on:

  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:


    - name: Clone wget source
      run: git clone https://github.com/mirror/wget.git

    - name: Install MSYS2
      uses: msys2/setup-msys2@v2
      with:
        update: true
        install: >-
          base-devel
          git
          autoconf
          automake
          libtool
          gperf
          gettext
          gettext-devel
          mingw-w64-x86_64-gettext
          mingw-w64-x86_64-gettext-devel
          texinfo
          pkg-config
          mingw-w64-x86_64-gcc
          mingw-w64-x86_64-make
          mingw-w64-x86_64-pkg-config
          mingw-w64-x86_64-libidn2
          mingw-w64-x86_64-libiconv
          mingw-w64-x86_64-openssl
          mingw-w64-x86_64-zlib


    - name: Build wget
      shell: msys2 {0}
      run: |
        cd wget
        ./bootstrap
        ./configure \
          --host=x86_64-w64-mingw32 \
          --with-ssl=openssl \
          --with-libidn2 \
          --enable-ipv6 \
          --enable-threads=posix \
          --disable-debug \
          --disable-nls \
          CFLAGS="-O2 -static" \
          LDFLAGS="-static"
        make -j$(nproc)
        strip src/wget.exe

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: wget-windows-x64
        path: wget/src/wget.exe
